/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.Test;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {
//    @Test public void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
////    }
//    @Test public void  testQuotes () {
//        Path path = Paths.get("C:\\Users\\LTUC\\lab8\\quotes\\app\\src\\main\\resources\\recentquotes.json");


    }

