/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import com.google.gson.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.FileReader;
import java.io.*;
import java.lang.reflect.Type;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws FileNotFoundException {
       Reader reader = new FileReader("recentquotes.json");

        Type quote = new TypeToken<List<Quotes>>(){}.getType();

        List<Quotes> quotes = new Gson().fromJson(reader,quote);
        int randomQuotes = (int)(Math.random() * (quotes.size()));
        System.out.println(quotes.get(randomQuotes));
        System.out.println("Author : " + quotes.get(randomQuotes).getAuthor());
        System.out.println("Quote : " + quotes.get(randomQuotes).getText());



    }
}
